IMPORT LIBARIES

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as pit

LOAD THE DATASET

In [4]:
df= pd.read_csv("/content/2-foodhub_order_New.csv")

In [5]:
df.tail(10)

,order_id,customer_id,restaurant_name,cuisine_type,cost_of_the_order,day_of_the_week,rating,food_preparation_time,delivery_time
1888,1477353,106324,The Meatball Shop,Italian,16.20,Weekend,5,21.0,26
1889,1478190,94152,RedFarm Broadway,Chinese,8.68,Weekday,3,33.0,30
1890,1477316,164776,TAO,Japanese,15.67,Weekend,5,20.0,22
1891,1476981,138586,Shake Shack,American,5.82,Weekend,Not given,22.0,28
1892,1477473,97838,Han Dynasty,Chinese,29.15,Weekend,Not given,29.0,21
1893,1476701,292602,Chipotle Mexican Grill $1.99 Delivery,Mexican,22.31,Weekend,5,31.0,17
1894,1477421,397537,The Smile,American,12.18,Weekend,5,31.0,19
1895,1477819,35309,Blue Ribbon Sushi,Japanese,25.22,Weekday,Not given,31.0,24
1896,1477513,64151,Jack's Wife Freda,Mediterranean,12.18,Weekday,5,23.0,31
1897,1478056,120353,Blue Ribbon Sushi,Japanese,19.45,Weekend,Not given,28.0,24

DATA PREPROCESSING

In [6]:
df.head(10)

,order_id,customer_id,restaurant_name,cuisine_type,cost_of_the_order,day_of_the_week,rating,food_preparation_time,delivery_time
0,1477147,337525,Hangawi,Korean,30.75,Weekend,Not given,25.0,20
1,1477685,358141,Blue Ribbon Sushi Izakaya,Japanese,12.08,Weekend,Not given,25.0,?
2,1477070,66393,Cafe Habana,Mexican,12.23,Weekday,5,23.0,28
3,1477334,106968,Blue Ribbon Fried Chicken,American,29.20,Weekend,3,25.0,15
4,1478249,76942,Dirty Bird to Go,American,11.59,Weekday,4,25.0,24
5,1477224,147468,Tamarind TriBeCa,Indian,25.22,Weekday,3,20.0,24
6,1477894,157711,The Meatball Shop,Italian,6.07,Weekend,Not given,28.0,21
7,1477859,89574,Barbounia,Mediterranean,5.97,Weekday,3,33.0,30
8,1477174,121706,Anjappar Chettinad,Indian,16.44,Weekday,5,21.0,26
9,1477311,39705,Bukhara Grill,Indian,7.18,Weekday,5,29.0,26

In [7]:
df. shape

(1898, 9)

In [8]:
df. info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1898 entries, 0 to 1897
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   order_id               1898 non-null   int64
 1   customer_id            1898 non-null   int64
 2   restaurant_name        1898 non-null   object
 3   cuisine_type           1895 non-null   object
 4   cost_of_the_order      1898 non-null   float64
 5   day_of_the_week        1898 non-null   object
 6   rating                 1898 non-null   object
 7   food_preparation_time  1896 non-null   float64
 8   delivery_time          1898 non-null   object
dtypes: float64(2), int64(2), object(5)
memory usage: 133.6+ KB

In [ ]:
print(df.dtypes)

order_id                   int64
customer_id                int64
restaurant_name           object
cuisine_type              object
cost_of_the_order        float64
day_of_the_week           object
rating                    object
food_preparation_time    float64
delivery_time             object
dtype: object

In [9]:
print(df.describe())

           order_id    customer_id  cost_of_the_order  food_preparation_time
count  1.898000e+03    1898.000000        1898.000000            1896.000000
mean   1.477496e+06  171168.478398          80.722007              27.371835
std    5.480497e+02  113698.139743        2798.141333               4.634211
min    1.476547e+06    1311.000000           0.000000              20.000000
25%    1.477021e+06   77787.750000          12.080000              23.000000
50%    1.477496e+06  128600.000000          14.160000              27.000000
75%    1.477970e+06  270525.000000          22.310000              31.000000
max    1.478444e+06  405334.000000      121920.000000              35.000000

In [10]:
null_values= df.isnull().sum()
print(null_values)

order_id                 0
customer_id              0
restaurant_name          0
cuisine_type             3
cost_of_the_order        0
day_of_the_week          0
rating                   0
food_preparation_time    2
delivery_time            0
dtype: int64

In [11]:
duplicate_row= df.duplicated().sum()
print("number of duplicated row: duplicated_row")

number of duplicated row: duplicated_row

In [12]:
numerical_columns = df.select_dtypes(include=['float64', 'int64']).columns

In [13]:
df.select_dtypes(include=['object']).columns

Index(['restaurant_name', 'cuisine_type', 'day_of_the_week', 'rating',
       'delivery_time'],
      dtype='object')

THE ANOMALIES OR WORNG ENTRIES

In [18]:
import pandas as pd
import numpy as np

# Load your dataset
df = pd.read_csv('/content/2-foodhub_order_New.csv')

# 1. Check for Missing Values
missing_values = df.isnull().sum()
print("Missing Values:\n", missing_values[missing_values > 0])

# 2. Check for Duplicate Rows
duplicate_rows = df[df.duplicated()]
print("Duplicate Rows:\n", duplicate_rows)

# 3. Detect Outliers
# Example for numeric columns
numeric_columns = df.select_dtypes(include=[np.number]).columns
Q1 = df[numeric_columns].quantile(0.25)
Q3 = df[numeric_columns].quantile(0.75)
IQR = Q3 - Q1
outliers = ((df[numeric_columns] < (Q1 - 1.5 * IQR)) | (df[numeric_columns] > (Q3 + 1.5 * IQR)))
print("Outliers:\n", outliers.any(axis=1))

# 4. Check for Data Type Inconsistencies
# Find the column you want to check for date type inconsistencies.
# Replace 'your_date_column' with the actual column name
# Example: Ensuring 'your_date_column' column is in datetime format
if 'your_date_column' in df.columns:
    df['your_date_column'] = pd.to_datetime(df['your_date_column'], errors='coerce')
    date_type_inconsistencies = df['your_date_column'].isnull()
    print("Date Type Inconsistencies:\n", df[date_type_inconsistencies])
else:
    print("Column 'your_date_column' not found in the DataFrame.")

# 5. Check for Value Range
# Example: Ensuring ages are within a realistic range (0-120)
if 'age' in df.columns:
    invalid_age = (df['age'] < 0) | (df['age'] > 120)
    print("Invalid Age Entries:\n", df[invalid_age])
else:
    print("Column 'age' not found in the DataFrame.")

# Summary of anomalies
print("Summary of Anomalies:")
print("Missing Values:\n", missing_values[missing_values > 0])
print("Duplicate Rows:\n", duplicate_rows)
print("Outliers:\n", outliers[outliers.any(axis=1)])
if 'your_date_column' in df.columns:
    print("Date Type Inconsistencies:\n", df[date_type_inconsistencies])
if 'age' in df.columns:
    print("Invalid Age Entries:\n", df[invalid_age])

Missing Values:
 cuisine_type             3
food_preparation_time    2
dtype: int64
Duplicate Rows:
 Empty DataFrame
Columns: [order_id, customer_id, restaurant_name, cuisine_type, cost_of_the_order, day_of_the_week, rating, food_preparation_time, delivery_time]
Index: []
Outliers:
 0       False
1       False
2       False
3       False
4       False
        ...
1893    False
1894    False
1895    False
1896    False
1897    False
Length: 1898, dtype: bool
Column 'your_date_column' not found in the DataFrame.
Column 'age' not found in the DataFrame.
Summary of Anomalies:
Missing Values:
 cuisine_type             3
food_preparation_time    2
dtype: int64
Duplicate Rows:
 Empty DataFrame
Columns: [order_id, customer_id, restaurant_name, cuisine_type, cost_of_the_order, day_of_the_week, rating, food_preparation_time, delivery_time]
Index: []
Outliers:
      order_id  customer_id  cost_of_the_order  food_preparation_time
214     False        False               True                  False

CHECK THE OUTLINER AND THEIR AUNTHENCITY

In [20]:
import pandas as pd
import numpy as np

# Load your dataset
df = pd.read_csv('/content/2-foodhub_order_New.csv')

# Function to detect outliers using IQR method
def detect_outliers_iqr(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    outliers = df[(df[column] < lower_bound) | (df[column] > upper_bound)]
    return outliers

# Detect outliers for each numeric column
numeric_columns = df.select_dtypes(include=[np.number]).columns
outliers_dict = {}
for column in numeric_columns:
    outliers = detect_outliers_iqr(df, column)
    if not outliers.empty:
        outliers_dict[column] = outliers

# Display outliers
for column, outliers in outliers_dict.items():
    print(f"Outliers in {column}:\n", outliers)

# Function to verify authenticity of outliers
def verify_outliers(df, column, outliers):
    # Hypothetical domain knowledge check
    if column == 'age':
        valid_range = (0, 120)
        return outliers[(outliers[column] >= valid_range[0]) & (outliers[column] <= valid_range[1])]
    elif column == 'salary':
        # Example: Salaries should be within a reasonable range, say (1000, 1000000)
        valid_range = (1000, 1000000)
        return outliers[(outliers[column] >= valid_range[0]) & (outliers[column] <= valid_range[1])]
    else:
        # For other columns, we might need different checks or additional context-specific logic
        return outliers

# Verify authenticity of outliers
verified_outliers_dict = {}
for column, outliers in outliers_dict.items():
    verified_outliers = verify_outliers(df, column, outliers)
    if not verified_outliers.empty:
        verified_outliers_dict[column] = verified_outliers

# Display verified outliers
for column, outliers in verified_outliers_dict.items():
    print(f"Verified outliers in {column}:\n", outliers)

Outliers in cost_of_the_order:
      order_id  customer_id restaurant_name cuisine_type  cost_of_the_order  \
214   1476598        41168            Parm      Italian           121920.0

    day_of_the_week rating  food_preparation_time delivery_time
214         Weekend      3                   34.0            22
Verified outliers in cost_of_the_order:
      order_id  customer_id restaurant_name cuisine_type  cost_of_the_order  \
214   1476598        41168            Parm      Italian           121920.0

    day_of_the_week rating  food_preparation_time delivery_time
214         Weekend      3                   34.0            22

DO THE DTA CLEANING STEPS LIKE DROPPING DUPPLICATE, UNNECESSARY COLUM, NULL VALUE IMPUTAATION OUTLINEAR TREATEMENT ETC

In [23]:
import pandas as pd
import numpy as np

# Load your dataset
df = pd.read_csv('/content/2-foodhub_order_New.csv')

# 1. Drop duplicate rows
df = df.drop_duplicates()

# 2. Remove unnecessary columns
# Specify the columns you want to drop
columns_to_drop = ['unnecessary_column1', 'unnecessary_column2']
df = df.drop(columns=columns_to_drop, errors='ignore')

# 3. Impute missing values
# Example: Fill numeric columns with the median value
numeric_columns = df.select_dtypes(include=[np.number]).columns
df[numeric_columns] = df[numeric_columns].fillna(df[numeric_columns].median())

# Example: Fill categorical columns with the mode (most frequent value)
categorical_columns = df.select_dtypes(include=[object]).columns
df[categorical_columns] = df[categorical_columns].apply(lambda x: x.fillna(x.mode()[0]))

# 4. Treat outliers using IQR method
def treat_outliers_iqr(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    df[column] = np.where(df[column] < lower_bound, lower_bound, df[column])
    df[column] = np.where(df[column] > upper_bound, upper_bound, df[column])
    return df

# Apply the IQR method to treat outliers for each numeric column
for column in numeric_columns:
    df = treat_outliers_iqr(df, column)

# 5. Additional data cleaning steps (if necessary)
# Convert date columns to datetime format
# Make sure the column names in 'date_columns' actually exist in your DataFrame
date_columns = ['replace_with_actual_date_column1', 'replace_with_actual_date_column2']  # Replace with actual column names
for column in date_columns:
    if column in df.columns:  # Check if column exists before conversion
        df[column] = pd.to_datetime(df[column], errors='coerce')
    else:
        print(f"Column '{column}' not found in DataFrame. Skipping conversion.")

# Reset index after cleaning
df.reset_index(drop=True, inplace=True)

# Display the cleaned dataset
print(df.head())

# Save the cleaned dataset to a new CSV file
df.to_csv('cleaned_dataset.csv', index=False)

Column 'replace_with_actual_date_column1' not found in DataFrame. Skipping conversion.
Column 'replace_with_actual_date_column2' not found in DataFrame. Skipping conversion.
    order_id  customer_id            restaurant_name cuisine_type  \
0  1477147.0     337525.0                    Hangawi       Korean
1  1477685.0     358141.0  Blue Ribbon Sushi Izakaya     Japanese
2  1477070.0      66393.0                Cafe Habana      Mexican
3  1477334.0     106968.0  Blue Ribbon Fried Chicken     American
4  1478249.0      76942.0           Dirty Bird to Go     American

   cost_of_the_order day_of_the_week     rating  food_preparation_time  \
0              30.75         Weekend  Not given                   25.0
1              12.08         Weekend  Not given                   25.0
2              12.23         Weekday          5                   23.0
3              29.20         Weekend          3                   25.0
4              11.59         Weekday          4                   25.0

  delivery_time
0            20
1             ?
2            28
3            15
4            24

ORDER ANALYSIS

TOTAL NUMBER OF IN THE DATASET

In [24]:
import pandas as pd

# Load your dataset
df = pd.read_csv('/content/2-foodhub_order_New.csv')

# Total number of rows (assuming each row is an individual order)
total_orders = len(df)

print(f"Total number of orders: {total_orders}")

Total number of orders: 1898

THE AVERAGE COST OF AN ORDER

In [26]:
import pandas as pd

# Load your dataset
df = pd.read_csv('/content/2-foodhub_order_New.csv')

# Check if 'quantity' and 'price_per_unit' columns exist
if 'quantity' in df.columns and 'price_per_unit' in df.columns:
    # Assuming 'quantity' and 'price_per_unit' are columns that can be used to calculate the order cost
    df['order_cost'] = df['quantity'] * df['price_per_unit']

    # Calculate the average order cost
    average_order_cost = df['order_cost'].mean()

    print(f"Average cost of an order: {average_order_cost}")
else:
    print("Error: 'quantity' or 'price_per_unit' column not found in the dataset.")

Error: 'quantity' or 'price_per_unit' column not found in the dataset.

UNIQUE CUSTOMER HAVE PLACED ORDER

In [28]:
import pandas as pd

# Load your dataset
df = pd.read_csv('/content/2-foodhub_order_New.csv')

# Assuming 'customer_id' is the column that uniquely identifies each customer
unique_customers = df['customer_id'].nunique()

print(f"Number of unique customers who have placed orders: {unique_customers}")

Number of unique customers who have placed orders: 1200

restaurant has received the highest number of orders

In [27]:
import pandas as pd

# Load your dataset
df = pd.read_csv('/content/2-foodhub_order_New.csv')

# Assuming 'restaurant_id' or 'restaurant_name' is the column that identifies each restaurant
# Replace 'restaurant_column' with the actual column name (e.g., 'restaurant_id' or 'restaurant_name')
restaurant_column = 'restaurant_name'

# Group by the restaurant column and count the number of orders for each restaurant
restaurant_order_counts = df[restaurant_column].value_counts()

# Find the restaurant with the highest number of orders
most_orders_restaurant = restaurant_order_counts.idxmax()
highest_order_count = restaurant_order_counts.max()

print(f"Restaurant with the highest number of orders: {most_orders_restaurant}")
print(f"Number of orders received by this restaurant: {highest_order_count}")

Restaurant with the highest number of orders: Shake Shack
Number of orders received by this restaurant: 219

CUSTOMER BEHAVIOUR

the average rating given by customers?

In [30]:
import pandas as pd

# Load your dataset
df = pd.read_csv('/content/2-foodhub_order_New.csv')

# Replace 'Not given' with NaN and convert the column to numeric
df['rating'] = pd.to_numeric(df['rating'], errors='coerce')

# Calculate the average rating, ignoring missing values
average_rating = df['rating'].mean()

print(f"Average rating given by customers: {average_rating:.2f}")

Average rating given by customers: 4.34

 the rating vary between weekdays and weekends

In [35]:
import pandas as pd

# Load your dataset
df = pd.read_csv('/content/2-foodhub_order_New.csv')

# Verify the column names in your DataFrame
print(df.columns)

# Replace 'actual_column_name' with the actual column name containing the date of each order
# You can use the variable 'column' here if it contains the correct column name
df[column] = pd.to_datetime(df[column])

# Extract the day of the week from the order_date
# Monday is 0 and Sunday is 6
df['day_of_week'] = df[column].dt.dayofweek

# Classify the days into weekdays (0-4) and weekends (5-6)
df['is_weekend'] = df['day_of_week'].apply(lambda x: 'Weekend' if x >= 5 else 'Weekday')

# Calculate the average rating for weekdays and weekends
average_ratings = df.groupby('is_weekend')['rating'].mean()

print("Average ratings on weekdays and weekends:")
print(average_ratings)

Index(['order_id', 'customer_id', 'restaurant_name', 'cuisine_type',
       'cost_of_the_order', 'day_of_the_week', 'rating',
       'food_preparation_time', 'delivery_time'],
      dtype='object')

KeyError: 'replace_with_actual_date_column2'

cuisine type is ordered the most

In [36]:
import pandas as pd

# Load your dataset
df = pd.read_csv('/content/2-foodhub_order_New.csv')

# Assuming 'cuisine_type' is the column that contains the cuisine type for each order
most_ordered_cuisine = df['cuisine_type'].value_counts().idxmax()
highest_order_count = df['cuisine_type'].value_counts().max()

print(f"Cuisine type ordered the most: {most_ordered_cuisine}")
print(f"Number of orders for this cuisine type: {highest_order_count}")

Cuisine type ordered the most: American
Number of orders for this cuisine type: 582

the distribution of orders across different days of the week

In [39]:
import pandas as pd
import matplotlib.pyplot as plt

# Load your dataset
df = pd.read_csv('/content/2-foodhub_order_New.csv')

# Verify the column names in your DataFrame
print(df.columns)

# Replace 'actual_order_date_column' with the actual column name containing the date
df['order_date'] = pd.to_datetime(df['actual_order_date_column'])

# Extract the day of the week from the order_date
# Monday is 0 and Sunday is 6
df['day_of_week'] = df['order_date'].dt.dayofweek

# Map the numeric day of the week to the actual day name
df['day_name'] = df['order_date'].dt.day_name()

# Count the number of orders for each day of the week
orders_by_day = df['day_name'].value_counts().reindex(
    ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
)

# Print the distribution of orders by day of the week
print("Distribution of orders by day of the week:")
print(orders_by_day)

# Plot the distribution of orders by day of the week
plt.figure(figsize=(10, 6))
orders_by_day.plot(kind='bar', color='skyblue')
plt.title('Distribution of Orders by Day of the Week')
plt.xlabel('Day of the Week')
plt.ylabel('Number of Orders')
plt.xticks(rotation=45)
plt.grid(axis='y')
plt.show()

Index(['order_id', 'customer_id', 'restaurant_name', 'cuisine_type',
       'cost_of_the_order', 'day_of_the_week', 'rating',
       'food_preparation_time', 'delivery_time'],
      dtype='object')

KeyError: 'actual_order_date_column'